# Generated by Django 4.1.2 on 2022-10-28 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SsulModel',
            fields=[
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='기타', max_length=20)),
                ('contents', models.CharField(max_length=1000)),
                ('left_option', models.CharField(max_length=20)),
                ('left_count', models.IntegerField(default=0)),
                ('right_option', models.CharField(max_length=20)),
                ('right_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('report_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRateSsul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('select_option', models.CharField(max_length=20)),
                ('ssul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssul.ssulmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
